# Generated by Django 6.0.1 on 2026-01-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysissession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='analysissession',
            name='approval_checkpoint',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='checkpoint_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='current_step',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analysissession',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('awaiting_approval', 'Awaiting Approval'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
    ]
