# backend/agents/report_generation.py
"""
Report generation agent.
Generates PDF reports combining all analysis results.
"""

import os
import asyncio
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from django.conf import settings

from workflows.state import AgentState, add_message, set_error
from workflows.retry import agent_retry


def create_pdf_report(
    session_id: int,
    analysis: str,
    compliance: str,
    risk: str,
    pages_count: int
) -> str:
    """
    Create a PDF report with all analysis results.
    """
    print(f"      → Creating PDF report for session {session_id}...")
    
    report_dir = os.path.join(settings.MEDIA_ROOT, 'reports')
    os.makedirs(report_dir, exist_ok=True)
    report_path = os.path.join(report_dir, f'report_{session_id}.pdf')
    
    print(f"      → Report path: {report_path}")
    
    # Create PDF
    c = canvas.Canvas(report_path, pagesize=letter)
    width, height = letter
    
    # Title
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, height - 50, f"Financial Analysis Report")
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 70, f"Session ID: {session_id}")
    
    # Horizontal line
    c.setStrokeColor(colors.grey)
    c.line(50, height - 85, width - 50, height - 85)
    
    # Document Overview
    y = height - 120
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Document Overview")
    c.setFont("Helvetica", 11)
    y -= 20
    c.drawString(70, y, f"Pages analyzed: {pages_count}")
    
    # Finance Analysis Section
    y -= 40
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Finance Analysis")
    c.setFont("Helvetica", 11)
    y -= 20
    for line in _wrap_text(analysis, 80):
        c.drawString(70, y, line)
        y -= 15
    
    # Compliance Section
    y -= 25
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Compliance Check")
    c.setFont("Helvetica", 11)
    y -= 20
    for line in _wrap_text(compliance, 80):
        c.drawString(70, y, line)
        y -= 15
    
    # Risk Assessment Section
    y -= 25
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Risk Assessment")
    c.setFont("Helvetica", 11)
    y -= 20
    for line in _wrap_text(risk, 80):
        c.drawString(70, y, line)
        y -= 15
    
    # Footer
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(50, 50, "Generated by Financial Analysis Agent")
    
    c.showPage()
    c.save()
    
    print(f"      ✅ PDF saved successfully")
    return report_path


def _wrap_text(text: str, max_chars: int) -> list[str]:
    """Wrap text to fit within max characters per line."""
    words = text.split()
    lines = []
    current_line = []
    current_length = 0
    
    for word in words:
        if current_length + len(word) + 1 <= max_chars:
            current_line.append(word)
            current_length += len(word) + 1
        else:
            if current_line:
                lines.append(" ".join(current_line))
            current_line = [word]
            current_length = len(word)
    
    if current_line:
        lines.append(" ".join(current_line))
    
    return lines if lines else [text]


@agent_retry(agent_name="report_generation")
async def process_async(state: AgentState) -> AgentState:
    """
    Async process function for report generation.
    """
    print("\n   📝 REPORT GENERATION AGENT")
    print("   " + "-"*40)
    
    state = add_message(state, "report_generation", "Report generation started")
    state["current_agent"] = "report_generation"
    
    session_id = state.get("session_id", 0)
    analysis = state.get("analysis_result", "No analysis available")
    compliance = state.get("compliance_result", "No compliance check available")
    risk = state.get("risk_result", "No risk assessment available")
    pages = state.get("pages", [])
    
    print(f"      Session: {session_id}")
    print(f"      Pages: {len(pages)}")
    print(f"      Analysis: {analysis[:40]}...")
    print(f"      Compliance: {compliance[:40]}...")
    print(f"      Risk: {risk[:40]}...")
    
    # Run PDF generation in thread pool
    loop = asyncio.get_event_loop()
    report_path = await loop.run_in_executor(
        None,
        create_pdf_report,
        session_id,
        analysis,
        compliance,
        risk,
        len(pages)
    )
    
    state["report_path"] = report_path
    state["status"] = "completed"
    
    print(f"   ✅ Report generated: {report_path}")
    state = add_message(state, "report_generation", "Report generation completed")
    return state


# Legacy sync process function
def process(session, analysis, compliance, risk, send_message):
    """Legacy synchronous process function."""
    send_message("Report generation started")
    
    report_dir = os.path.join(settings.MEDIA_ROOT, 'reports')
    os.makedirs(report_dir, exist_ok=True)
    report_path = os.path.join(report_dir, f'report_{session.id}.pdf')
    
    c = canvas.Canvas(report_path)
    c.setFont("Helvetica", 14)
    c.drawString(100, 800, f"Financial Analysis Report - Session {session.id}")
    c.setFont("Helvetica", 12)
    c.drawString(100, 760, f"Finance Analysis: {analysis}")
    c.drawString(100, 740, f"Compliance Check: {compliance}")
    c.drawString(100, 720, f"Risk Assessment: {risk}")
    c.showPage()
    c.save()
    
    session.report_file = report_path
    session.status = 'completed'
    session.save()
    send_message("Report generation completed")
