# backend/agents/report_generation.py
"""
Report generation agent.
Generates professional PDF reports using ReportLab Platypus (flowable layout):
real tables, automatic wrapping, automatic page breaks, and a running footer.
"""

import os
import math
import asyncio

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable, KeepTogether,
)

from django.conf import settings

from workflows.state import AgentState, add_message, set_error
from workflows.retry import agent_retry


# --- Palette (single source of truth for the corporate look) ---
NAVY   = colors.HexColor("#1F2D3D")
SLATE  = colors.HexColor("#34495E")
BLUE   = colors.HexColor("#2E86DE")
GREY   = colors.HexColor("#6B7280")
LIGHT  = colors.HexColor("#F1F4F8")
ZEBRA  = colors.HexColor("#F7F9FC")
GREEN  = colors.HexColor("#1E9E62")
AMBER  = colors.HexColor("#E08A1E")
RED    = colors.HexColor("#D64541")
LINE   = colors.HexColor("#D9E0E7")


def _styles():
    """Build the paragraph styles used throughout the report."""
    ss = getSampleStyleSheet()
    styles = {
        "title":    ParagraphStyle("title", parent=ss["Title"], fontName="Helvetica-Bold",
                                   fontSize=26, textColor=NAVY, spaceAfter=6, alignment=TA_CENTER),
        "subtitle": ParagraphStyle("subtitle", parent=ss["Normal"], fontSize=12,
                                   textColor=GREY, alignment=TA_CENTER, spaceAfter=2),
        "h1":       ParagraphStyle("h1", parent=ss["Heading1"], fontName="Helvetica-Bold",
                                   fontSize=15, textColor=NAVY, spaceBefore=6, spaceAfter=8),
        "h2":       ParagraphStyle("h2", parent=ss["Heading2"], fontName="Helvetica-Bold",
                                   fontSize=11.5, textColor=SLATE, spaceBefore=10, spaceAfter=5),
        "body":     ParagraphStyle("body", parent=ss["Normal"], fontSize=9.5,
                                   textColor=colors.HexColor("#222B36"), leading=14, spaceAfter=4),
        "small":    ParagraphStyle("small", parent=ss["Normal"], fontSize=8.5,
                                   textColor=GREY, leading=12),
        "cell":     ParagraphStyle("cell", parent=ss["Normal"], fontSize=9, leading=12),
        "cellb":    ParagraphStyle("cellb", parent=ss["Normal"], fontSize=9, leading=12,
                                   fontName="Helvetica-Bold", textColor=SLATE),
        "kpi_lbl":  ParagraphStyle("kpi_lbl", parent=ss["Normal"], fontSize=9,
                                   textColor=colors.white, alignment=TA_CENTER),
        "kpi_val":  ParagraphStyle("kpi_val", parent=ss["Normal"], fontName="Helvetica-Bold",
                                   fontSize=20, textColor=colors.white, alignment=TA_CENTER),
    }
    return styles


def _section(title, styles):
    """A section header: blue rule above a bold navy title, kept together."""
    return KeepTogether([
        HRFlowable(width="100%", thickness=2, color=BLUE, spaceBefore=4, spaceAfter=6),
        Paragraph(title, styles["h1"]),
    ])


def _status_chip(text, color):
    """Inline colored status text for table cells."""
    return f'<font color="{color.hexval()}"><b>{text}</b></font>'


def create_pdf_report(
    session_id: int,
    analysis: str,
    compliance: str,
    risk: str,
    pages_count: int,
    audit_report: dict = None,
    risk_report: dict = None,
    financial_extraction: dict = None
) -> str:
    """Create a professional, flowable-based PDF report with all analysis results."""
    print(f"      → Creating PDF report for session {session_id}...")

    report_dir = os.path.join(settings.MEDIA_ROOT, 'reports')
    os.makedirs(report_dir, exist_ok=True)
    report_path = os.path.join(report_dir, f'report_{session_id}.pdf')

    styles = _styles()
    width, height = letter

    # Shared parser (same one the finance agent uses) for margins/YoY consistency
    try:
        from agents.finance_analysis import _parse_financial_value
    except Exception:
        def _parse_financial_value(_):  # fallback if import path differs
            return float('nan')

    # --- Running header/footer, drawn on every page ---
    def _decorate(canvas, doc):
        canvas.saveState()
        # Footer
        canvas.setStrokeColor(LINE)
        canvas.setLineWidth(0.5)
        canvas.line(50, 42, width - 50, 42)
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(GREY)
        canvas.drawString(50, 30, "Generated by Financial Analysis Agent")
        canvas.drawCentredString(width / 2, 30, f"Session {session_id}")
        canvas.drawRightString(width - 50, 30, f"Page {doc.page}")
        canvas.restoreState()

    doc = SimpleDocTemplate(
        report_path, pagesize=letter,
        leftMargin=54, rightMargin=54, topMargin=58, bottomMargin=54,
        title=f"Financial Analysis Report - Session {session_id}",
    )
    content_w = doc.width
    story = []

    # ============================================================= TITLE
    story.append(Spacer(1, 90))
    story.append(Paragraph("Financial Analysis Report", styles["title"]))
    story.append(Paragraph("Automated Multi-Agent Analysis", styles["subtitle"]))
    story.append(Spacer(1, 6))
    story.append(HRFlowable(width="40%", thickness=1, color=LINE,
                            spaceBefore=6, spaceAfter=18, hAlign="CENTER"))
    meta = Table(
        [[Paragraph("Session ID", styles["small"]), Paragraph(str(session_id), styles["cellb"])],
         [Paragraph("Pages Analyzed", styles["small"]), Paragraph(str(pages_count), styles["cellb"])]],
        colWidths=[110, 110], hAlign="CENTER",
    )
    meta.setStyle(TableStyle([
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(meta)
    story.append(Spacer(1, 34))

    # --- Executive Summary KPI band ---
    if audit_report or risk_report:
        story.append(Paragraph("Executive Summary", styles["h2"]))
        story.append(Spacer(1, 4))

        cells, widths = [], []
        if audit_report:
            cs = audit_report.get('compliance_score', 0)
            c_col = GREEN if cs >= 80 else AMBER if cs >= 60 else RED
            cells.append(("COMPLIANCE", f"{cs}/100", c_col))
        if risk_report:
            rs = risk_report.get('risk_score', 0)
            lvl = risk_report.get('risk_level', 'N/A')
            r_col = GREEN if rs < 30 else AMBER if rs < 60 else RED
            cells.append(("RISK", f"{rs}/100\n{lvl}", r_col))

        kpi_row, style_cmds = [], [
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 12),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ]
        inner = []
        for i, (lbl, val, col) in enumerate(cells):
            block = Table(
                [[Paragraph(lbl, styles["kpi_lbl"])],
                 [Paragraph(val.replace("\n", "<br/>"), styles["kpi_val"])]],
                colWidths=[content_w / len(cells) - 12],
            )
            block.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), col),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 10),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
                ("ROUNDEDCORNERS", [6, 6, 6, 6]),
            ]))
            inner.append(block)
        band = Table([inner], colWidths=[content_w / len(inner)] * len(inner))
        band.setStyle(TableStyle([
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]))
        story.append(band)

    story.append(PageBreak())

    # ============================================================= FINANCE
    story.append(_section("Finance Analysis", styles))

    # Split narrative from the RAG Q&A block
    main_analysis, rag_content = analysis, None
    if "[RAG Q&A]" in analysis:
        parts = analysis.split("[RAG Q&A]")
        main_analysis = parts[0].strip()
        if len(parts) > 1:
            rag_content = parts[1].strip()

    for para in [p for p in main_analysis.split("\n") if p.strip()]:
        story.append(Paragraph(para.strip(), styles["body"]))
    story.append(Spacer(1, 6))

    if rag_content:
        story.append(Paragraph("Q&amp;A with Finance Agent", styles["h2"]))
        for para in [p for p in rag_content.split("\n") if p.strip()]:
            story.append(Paragraph(para.strip().replace("&", "&amp;"), styles["body"]))
        story.append(Spacer(1, 6))

    # ============================================================= COMPLIANCE (summary)
    story.append(_section("Compliance Check", styles))
    for para in [p for p in compliance.split("\n") if p.strip()]:
        story.append(Paragraph(para.strip(), styles["body"]))

    # ============================================================= RISK (summary)
    story.append(_section("Risk Assessment", styles))
    for para in [p for p in risk.split("\n") if p.strip()]:
        story.append(Paragraph(para.strip(), styles["body"]))

    # ============================================================= DETAILED FINANCE
    fs = (financial_extraction or {}).get('financial_summary', {})
    periods = fs.get('periods', []) if isinstance(fs, dict) else []
    if financial_extraction:
        story.append(PageBreak())
        story.append(_section("Detailed Finance Analysis", styles))

        if periods:
            story.append(Paragraph("Financial Performance Summary", styles["h2"]))
            disp = periods[:3]

            def yoy(key):
                if len(disp) < 2:
                    return "—"
                n = _parse_financial_value(disp[0].get(key))
                o = _parse_financial_value(disp[1].get(key))
                if not math.isnan(n) and not math.isnan(o) and o != 0:
                    return f"{(n - o) / abs(o):+.1%}"
                return "—"

            header = ["Metric"] + [str(p.get("period", "N/A")) for p in disp]
            if len(disp) >= 2:
                header.append("YoY %")

            rows = [[Paragraph(h, styles["cellb"]) for h in header]]
            metric_map = [("Total Revenue", "revenue"), ("Net Income", "net_income"),
                          ("Total Assets", "total_assets"), ("Total Liabilities", "total_liabilities"),
                          ("Total Equity", "total_equity"), ("Debt-to-Equity", "debt_to_equity")]
            for label, key in metric_map:
                row = [Paragraph(label, styles["cellb"])]
                row += [Paragraph(str(p.get(key, "N/A")), styles["cell"]) for p in disp]
                if len(disp) >= 2:
                    row.append(Paragraph(yoy(key), styles["cell"]))
                rows.append(row)

            # Computed Net Margin row
            margin_row = [Paragraph("Net Margin", styles["cellb"])]
            for p in disp:
                rev = _parse_financial_value(p.get("revenue"))
                ni = _parse_financial_value(p.get("net_income"))
                margin_row.append(Paragraph(
                    f"{ni / rev:.1%}" if (not math.isnan(rev) and rev != 0 and not math.isnan(ni)) else "N/A",
                    styles["cell"]))
            if len(disp) >= 2:
                margin_row.append(Paragraph("—", styles["cell"]))
            rows.append(margin_row)

            ncols = len(header)
            first = content_w * 0.30
            rest = (content_w - first) / (ncols - 1)
            t = Table(rows, colWidths=[first] + [rest] * (ncols - 1), hAlign="LEFT", repeatRows=1)
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), NAVY),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, ZEBRA]),
                ("LINEBELOW", (0, 0), (-1, -1), 0.4, LINE),
                ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ]))
            story.append(t)
            story.append(Spacer(1, 10))

        numbers = financial_extraction.get('numbers', [])
        if numbers:
            story.append(Paragraph("Key Extracted Figures &amp; Ratios", styles["h2"]))
            for n in numbers:
                story.append(Paragraph(f"• {n}", styles["body"]))
            story.append(Spacer(1, 6))

        dates = financial_extraction.get('important_dates', [])
        if dates:
            story.append(Paragraph(f"Significant Dates ({len(dates)})", styles["h2"]))
            rows = [[Paragraph("Date", styles["cellb"]), Paragraph("Event / Context", styles["cellb"])]]
            for d in dates:
                rows.append([Paragraph(str(d.get('date', 'N/A')), styles["cell"]),
                             Paragraph(str(d.get('significance', 'N/A')), styles["cell"])])
            t = Table(rows, colWidths=[content_w * 0.28, content_w * 0.72], repeatRows=1, hAlign="LEFT")
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), SLATE),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, ZEBRA]),
                ("LINEBELOW", (0, 0), (-1, -1), 0.4, LINE),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ]))
            story.append(t)
            story.append(Spacer(1, 8))

        companies = financial_extraction.get('companies', [])
        currencies = financial_extraction.get('currencies', [])
        if companies or currencies:
            story.append(Paragraph("Entities &amp; Currency", styles["h2"]))
            if companies:
                story.append(Paragraph(f"<b>Companies:</b> {', '.join(companies)}", styles["body"]))
            if currencies:
                story.append(Paragraph(f"<b>Reporting Currencies:</b> {', '.join(currencies)}", styles["body"]))

    # ============================================================= DETAILED COMPLIANCE
    if audit_report:
        story.append(PageBreak())
        story.append(_section("Detailed Compliance Audit", styles))

        cs = audit_report.get('compliance_score', 0)
        c_col = GREEN if cs >= 80 else AMBER if cs >= 60 else RED
        story.append(Paragraph(
            f'Overall Compliance Score: {_status_chip(f"{cs}/100", c_col)}', styles["body"]))
        story.append(Spacer(1, 6))

        rules = audit_report.get('rules_check', [])
        if rules:
            story.append(Paragraph(f"Compliance Checks Verified ({len(rules)})", styles["h2"]))
            rows = [[Paragraph(h, styles["cellb"]) for h in ("Check", "Status", "Evidence")]]
            for r in rules:
                status = r.get('status', 'Unknown')
                s_col = GREEN if status == 'Compliant' else RED if status == 'Non-Compliant' else AMBER
                check_name = r.get('name') or r.get('requirement') or r.get('rule_id', 'N/A')
                name_cell = f'<b>{r.get("rule_id", "")}</b> &nbsp;{check_name}'
                evidence = r.get('evidence', '') or '—'
                rows.append([
                    Paragraph(name_cell, styles["cell"]),
                    Paragraph(_status_chip(status, s_col), styles["cell"]),
                    Paragraph(evidence, styles["cell"]),
                ])
            t = Table(rows, colWidths=[content_w * 0.34, content_w * 0.16, content_w * 0.50],
                      repeatRows=1, hAlign="LEFT")
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), NAVY),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, ZEBRA]),
                ("LINEBELOW", (0, 0), (-1, -1), 0.4, LINE),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ]))
            story.append(t)
            story.append(Spacer(1, 8))

        # Audit Trail (previously extracted but never rendered)
        trail = audit_report.get('audit_trail', '')
        if trail:
            story.append(Paragraph("Audit Trail", styles["h2"]))
            trail_lines = [ln.strip() for ln in str(trail).replace(';', '\n').split('\n') if ln.strip()]
            for ln in trail_lines:
                story.append(Paragraph(f"• {ln}", styles["small"]))
            story.append(Spacer(1, 8))

        flags = audit_report.get('risk_flags', [])
        if flags:
            story.append(Paragraph(f"Identified Risk Flags ({len(flags)})", styles["h2"]))
            for f in flags:
                sev = f.get('severity', 'Unknown')
                s_col = RED if sev == 'High' else AMBER if sev == 'Medium' else GREEN
                story.append(Paragraph(
                    f'{_status_chip(sev.upper(), s_col)} &nbsp;<b>{f.get("risk_type", "N/A")}</b> — '
                    f'{f.get("description", "")}', styles["body"]))
            story.append(Spacer(1, 6))

        annotations = audit_report.get('annotations', [])
        if annotations:
            story.append(Paragraph("Recommendations", styles["h2"]))
            for i, a in enumerate(annotations[:5], 1):
                story.append(Paragraph(f"{i}. {a}", styles["body"]))

    # ============================================================= DETAILED RISK
    if risk_report:
        story.append(PageBreak())
        story.append(_section("Detailed Risk Assessment", styles))

        rs = risk_report.get('risk_score', 0)
        lvl = risk_report.get('risk_level', 'N/A')
        r_col = GREEN if rs < 30 else AMBER if rs < 60 else RED
        story.append(Paragraph(
            f'Risk Score: {_status_chip(f"{rs}/100 ({lvl})", r_col)}', styles["body"]))
        story.append(Spacer(1, 6))

        ratios = risk_report.get('ratios', [])
        if ratios:
            story.append(Paragraph("Financial Ratios", styles["h2"]))
            rows = [[Paragraph(h, styles["cellb"]) for h in ("Ratio", "Period", "Value", "Meaning")]]
            for r in ratios:
                val = r.get('value')
                val_str = f"{val:.2f}" if isinstance(val, (int, float)) and val == val else "N/A"
                rows.append([
                    Paragraph(str(r.get('name', 'N/A')), styles["cell"]),
                    Paragraph(str(r.get('period', 'N/A')), styles["cell"]),
                    Paragraph(val_str, styles["cell"]),
                    Paragraph(str(r.get('description', '')), styles["small"]),
                ])
            t = Table(rows, colWidths=[content_w * 0.20, content_w * 0.12, content_w * 0.12, content_w * 0.56],
                      repeatRows=1, hAlign="LEFT")
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), NAVY),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, ZEBRA]),
                ("LINEBELOW", (0, 0), (-1, -1), 0.4, LINE),
                ("ALIGN", (2, 0), (2, -1), "RIGHT"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ]))
            story.append(t)
            story.append(Spacer(1, 8))

        anomalies = risk_report.get('anomalies', [])
        if anomalies:
            story.append(Paragraph(f"Detected Anomalies ({len(anomalies)})", styles["h2"]))
            for a in anomalies:
                sev = a.get('severity', 'Medium')
                s_col = RED if sev == 'High' else AMBER if sev == 'Medium' else GREEN
                change = a.get('yoy_change', 0)
                pf, pt = a.get('period_from', ''), a.get('period_to', '')
                pair = f" ({pf}\u2192{pt})" if pf else ""
                story.append(Paragraph(
                    f'{_status_chip("●", s_col)} <b>{a.get("item", "N/A")}</b>: '
                    f'{change:+.1%} change{pair}', styles["body"]))
            story.append(Spacer(1, 6))

        insights = risk_report.get('key_insights', [])
        if insights:
            story.append(Paragraph("Key Insights", styles["h2"]))
            for ins in insights[:6]:
                story.append(Paragraph(f"• {ins}", styles["body"]))

    # Build with the running footer on every page
    doc.build(story, onFirstPage=_decorate, onLaterPages=_decorate)
    print(f"      ✅ PDF saved successfully")
    return report_path


@agent_retry(agent_name="report_generation")
async def process_async(state: AgentState) -> AgentState:
    """
    Async process function for report generation.
    1. Aggregates analysis results (finance, compliance, risk).
    2. Generates a comprehensive PDF report using ReportLab Platypus.
    3. Updates state with the report path and marks workflow as completed.
    """
    print("\n   📝 REPORT GENERATION AGENT")
    print("   " + "-" * 40)

    state = add_message(state, "report_generation", "Report generation started")
    state["current_agent"] = "report_generation"

    session_id = state.get("session_id", 0)
    analysis = state.get("analysis_result", "No analysis available")
    compliance = state.get("compliance_result", "No compliance check available")
    risk = state.get("risk_result", "No risk assessment available")
    pages = state.get("pages", [])

    print(f"      Session: {session_id}")
    print(f"      Pages: {len(pages)}")

    audit_report = state.get("audit_report")
    risk_report = state.get("risk_report")
    print(f"      Audit report: {'Yes' if audit_report else 'No'}")
    print(f"      Risk report: {'Yes' if risk_report else 'No'}")

    loop = asyncio.get_event_loop()
    from functools import partial
    pdf_func = partial(
        create_pdf_report,
        session_id, analysis, compliance, risk, len(pages),
        audit_report, risk_report, state.get("financial_extraction"),
    )
    report_path = await loop.run_in_executor(None, pdf_func)

    state["report_path"] = report_path
    state["status"] = "completed"
    print(f"   ✅ Report generated: {report_path}")

    from api.models import AnalysisSession

    def update_report_file(sid, path):
        AnalysisSession.objects.filter(pk=sid).update(report_file=path)

    await loop.run_in_executor(None, update_report_file, session_id, report_path)
    print(f"   💾 Report saved to database")

    state = add_message(state, "report_generation", "Report generation completed")
    return state


# Legacy sync process function
def process(session, analysis, compliance, risk, send_message):
    """Legacy synchronous process function (kept for backward compatibility)."""
    send_message("Report generation started")
    create_pdf_report(session.id, analysis, compliance, risk, 0)
    session.report_file = os.path.join(settings.MEDIA_ROOT, 'reports', f'report_{session.id}.pdf')
    session.status = 'completed'
    session.save()
    send_message("Report generation completed")